import { graphql, useStaticQuery } from "gatsby";

const siteMeta = graphql`
  query TypegenMetaData {
    site {
      siteMetadata {
        description
        keywords
        title
      }
    }
  }
`;

export function useSiteMeta() {
  // Note autogenerated Queries type. Appending `Typegen` before query name is mandatory for this as above
  return useStaticQuery<Queries.TypegenMetaDataQuery>(siteMeta);
}
